use mkv::ElementType::*;

#[derive(Debug,Eq,PartialEq,Copy,Clone)]
pub enum Class {
    EBML,
    EBMLVersion,
    EBMLReadVersion,
    EBMLMaxIDLength,
    EBMLMaxSizeLength,
    DocType,
    DocTypeVersion,
    DocTypeReadVersion,
    Void,
    CRC32,
    SignatureSlot,
    SignatureAlgo,
    SignatureHash,
    SignaturePublicKey,
    Signature,
    SignatureElements,
    SignatureElementList,
    SignedElement,
    Segment,
    SeekHead,
    Seek,
    SeekID,
    SeekPosition,
    Info,
    SegmentUID,
    SegmentFilename,
    PrevUID,
    PrevFilename,
    NextUID,
    NextFilename,
    SegmentFamily,
    ChapterTranslate,
    ChapterTranslateEditionUID,
    ChapterTranslateCodec,
    ChapterTranslateID,
    TimecodeScale,
    Duration,
    DateUTC,
    Title,
    MuxingApp,
    WritingApp,
    Cluster,
    Timecode,
    SilentTracks,
    SilentTrackNumber,
    Position,
    PrevSize,
    SimpleBlock,
    BlockGroup,
    Block,
    BlockVirtual,
    BlockAdditions,
    BlockMore,
    BlockAddID,
    BlockAdditional,
    BlockDuration,
    ReferencePriority,
    ReferenceBlock,
    ReferenceVirtual,
    CodecState,
    Slices,
    TimeSlice,
    LaceNumber,
    FrameNumber,
    BlockAdditionID,
    Delay,
    SliceDuration,
    ReferenceFrame,
    ReferenceOffset,
    ReferenceTimeCode,
    EncryptedBlock,
    Tracks,
    TrackEntry,
    TrackNumber,
    TrackUID,
    TrackType,
    FlagEnabled,
    FlagDefault,
    FlagForced,
    FlagLacing,
    MinCache,
    MaxCache,
    DefaultDuration,
    TrackTimecodeScale,
    TrackOffset,
    MaxBlockAdditionID,
    Name,
    Language,
    CodecID,
    CodecPrivate,
    CodecName,
    AttachmentLink,
    CodecSettings,
    CodecInfoURL,
    CodecDownloadURL,
    CodecDecodeAll,
    TrackOverlay,
    TrackTranslate,
    TrackTranslateEditionUID,
    TrackTranslateCodec,
    TrackTranslateTrackID,
    Video,
    FlagInterlaced,
    StereoMode,
    OldStereoMode,
    PixelWidth,
    PixelHeight,
    PixelCropBottom,
    PixelCropTop,
    PixelCropLeft,
    PixelCropRight,
    DisplayWidth,
    DisplayHeight,
    DisplayUnit,
    AspectRatioType,
    ColourSpace,
    GammaValue,
    FrameRate,
    Audio,
    SamplingFrequency,
    OutputSamplingFrequency,
    Channels,
    ChannelPositions,
    BitDepth,
    TrackOperation,
    TrackCombinePlanes,
    TrackPlane,
    TrackPlaneUID,
    TrackPlaneType,
    TrackJoinBlocks,
    TrackJoinUID,
    TrickTrackUID,
    TrickTrackSegmentUID,
    TrickTrackFlag,
    TrickMasterTrackUID,
    TrickMasterTrackSegmentUID,
    ContentEncodings,
    ContentEncoding,
    ContentEncodingOrder,
    ContentEncodingScope,
    ContentEncodingType,
    ContentCompression,
    ContentCompAlgo,
    ContentCompSettings,
    ContentEncryption,
    ContentEncAlgo,
    ContentEncKeyID,
    ContentSignature,
    ContentSigKeyID,
    ContentSigAlgo,
    ContentSigHashAlgo,
    Cues,
    CuePoint,
    CueTime,
    CueTrackPositions,
    CueTrack,
    CueClusterPosition,
    CueBlockNumber,
    CueCodecState,
    CueReference,
    CueRefTime,
    CueRefCluster,
    CueRefNumber,
    CueRefCodecState,
    Attachments,
    AttachedFile,
    FileDescription,
    FileName,
    FileMimeType,
    FileData,
    FileUID,
    FileReferral,
    FileUsedStartTime,
    FileUsedEndTime,
    Chapters,
    EditionEntry,
    EditionUID,
    EditionFlagHidden,
    EditionFlagDefault,
    EditionFlagOrdered,
    ChapterAtom,
    ChapterUID,
    ChapterTimeStart,
    ChapterTimeEnd,
    ChapterFlagHidden,
    ChapterFlagEnabled,
    ChapterSegmentUID,
    ChapterSegmentEditionUID,
    ChapterPhysicalEquiv,
    ChapterTrack,
    ChapterTrackNumber,
    ChapterDisplay,
    ChapString,
    ChapLanguage,
    ChapCountry,
    ChapProcess,
    ChapProcessCodecID,
    ChapProcessPrivate,
    ChapProcessCommand,
    ChapProcessTime,
    ChapProcessData,
    Tags,
    Tag,
    Targets,
    TargetTypeValue,
    TargetType,
    TagTrackUID,
    TagEditionUID,
    TagChapterUID,
    TagAttachmentUID,
    SimpleTag,
    TagName,
    TagLanguage,
    TagDefault,
    TagString,
    TagBinary,
    Unknown,
}

pub fn id_to_class(id:u64) -> Class {
    use self::Class::*;
    
    match id {
       0x1A45DFA3 => EBML                        ,
       0x00004286 => EBMLVersion                 ,
       0x000042F7 => EBMLReadVersion             ,
       0x000042F2 => EBMLMaxIDLength             ,
       0x000042F3 => EBMLMaxSizeLength           ,
       0x00004282 => DocType                     ,
       0x00004287 => DocTypeVersion              ,
       0x00004285 => DocTypeReadVersion          ,
       0x000000EC => Void                        ,
       0x000000BF => CRC32                       ,
       0x1B538667 => SignatureSlot               ,
       0x00007E8A => SignatureAlgo               ,
       0x00007E9A => SignatureHash               ,
       0x00007EA5 => SignaturePublicKey          ,
       0x00007EB5 => Signature                   ,
       0x00007E5B => SignatureElements           ,
       0x00007E7B => SignatureElementList        ,
       0x00006532 => SignedElement               ,
       0x18538067 => Segment                     ,
       0x114D9B74 => SeekHead                    ,
       0x00004DBB => Seek                        ,
       0x000053AB => SeekID                      ,
       0x000053AC => SeekPosition                ,
       0x1549A966 => Info                        ,
       0x000073A4 => SegmentUID                  ,
       0x00007384 => SegmentFilename             ,
       0x003CB923 => PrevUID                     ,
       0x003C83AB => PrevFilename                ,
       0x003EB923 => NextUID                     ,
       0x003E83BB => NextFilename                ,
       0x00004444 => SegmentFamily               ,
       0x00006924 => ChapterTranslate            ,
       0x000069FC => ChapterTranslateEditionUID  ,
       0x000069BF => ChapterTranslateCodec       ,
       0x000069A5 => ChapterTranslateID          ,
       0x002AD7B1 => TimecodeScale               ,
       0x00004489 => Duration                    ,
       0x00004461 => DateUTC                     ,
       0x00007BA9 => Title                       ,
       0x00004D80 => MuxingApp                   ,
       0x00005741 => WritingApp                  ,
       0x1F43B675 => Cluster                     ,
       0x000000E7 => Timecode                    ,
       0x00005854 => SilentTracks                ,
       0x000058D7 => SilentTrackNumber           ,
       0x000000A7 => Position                    ,
       0x000000AB => PrevSize                    ,
       0x000000A3 => SimpleBlock                 ,
       0x000000A0 => BlockGroup                  ,
       0x000000A1 => Block                       ,
       0x000000A2 => BlockVirtual                ,
       0x000075A1 => BlockAdditions              ,
       0x000000A6 => BlockMore                   ,
       0x000000EE => BlockAddID                  ,
       0x000000A5 => BlockAdditional             ,
       0x0000009B => BlockDuration               ,
       0x000000FA => ReferencePriority           ,
       0x000000FB => ReferenceBlock              ,
       0x000000FD => ReferenceVirtual            ,
       0x000000A4 => CodecState                  ,
       0x0000008E => Slices                      ,
       0x000000E8 => TimeSlice                   ,
       0x000000CC => LaceNumber                  ,
       0x000000CD => FrameNumber                 ,
       0x000000CB => BlockAdditionID             ,
       0x000000CE => Delay                       ,
       0x000000CF => SliceDuration               ,
       0x000000C8 => ReferenceFrame              ,
       0x000000C9 => ReferenceOffset             ,
       0x000000CA => ReferenceTimeCode           ,
       0x000000AF => EncryptedBlock              ,
       0x1654AE6B => Tracks                      ,
       0x000000AE => TrackEntry                  ,
       0x000000D7 => TrackNumber                 ,
       0x000073C5 => TrackUID                    ,
       0x00000083 => TrackType                   ,
       0x000000B9 => FlagEnabled                 ,
       0x00000088 => FlagDefault                 ,
       0x000055AA => FlagForced                  ,
       0x0000009C => FlagLacing                  ,
       0x00006DE7 => MinCache                    ,
       0x00006DF8 => MaxCache                    ,
       0x0023E383 => DefaultDuration             ,
       0x0023314F => TrackTimecodeScale          ,
       0x0000537F => TrackOffset                 ,
       0x000055EE => MaxBlockAdditionID          ,
       0x0000536E => Name                        ,
       0x0022B59C => Language                    ,
       0x00000086 => CodecID                     ,
       0x000063A2 => CodecPrivate                ,
       0x00258688 => CodecName                   ,
       0x00007446 => AttachmentLink              ,
       0x003A9697 => CodecSettings               ,
       0x003B4040 => CodecInfoURL                ,
       0x0026B240 => CodecDownloadURL            ,
       0x000000AA => CodecDecodeAll              ,
       0x00006FAB => TrackOverlay                ,
       0x00006624 => TrackTranslate              ,
       0x000066FC => TrackTranslateEditionUID    ,
       0x000066BF => TrackTranslateCodec         ,
       0x000066A5 => TrackTranslateTrackID       ,
       0x000000E0 => Video                       ,
       0x0000009A => FlagInterlaced              ,
       0x000053B8 => StereoMode                  ,
       0x000053B9 => OldStereoMode               ,
       0x000000B0 => PixelWidth                  ,
       0x000000BA => PixelHeight                 ,
       0x000054AA => PixelCropBottom             ,
       0x000054BB => PixelCropTop                ,
       0x000054CC => PixelCropLeft               ,
       0x000054DD => PixelCropRight              ,
       0x000054B0 => DisplayWidth                ,
       0x000054BA => DisplayHeight               ,
       0x000054B2 => DisplayUnit                 ,
       0x000054B3 => AspectRatioType             ,
       0x002EB524 => ColourSpace                 ,
       0x002FB523 => GammaValue                  ,
       0x002383E3 => FrameRate                   ,
       0x000000E1 => Audio                       ,
       0x000000B5 => SamplingFrequency           ,
       0x000078B5 => OutputSamplingFrequency     ,
       0x0000009F => Channels                    ,
       0x00007D7B => ChannelPositions            ,
       0x00006264 => BitDepth                    ,
       0x000000E2 => TrackOperation              ,
       0x000000E3 => TrackCombinePlanes          ,
       0x000000E4 => TrackPlane                  ,
       0x000000E5 => TrackPlaneUID               ,
       0x000000E6 => TrackPlaneType              ,
       0x000000E9 => TrackJoinBlocks             ,
       0x000000ED => TrackJoinUID                ,
       0x000000C0 => TrickTrackUID               ,
       0x000000C1 => TrickTrackSegmentUID        ,
       0x000000C6 => TrickTrackFlag              ,
       0x000000C7 => TrickMasterTrackUID         ,
       0x000000C4 => TrickMasterTrackSegmentUID  ,
       0x00006D80 => ContentEncodings            ,
       0x00006240 => ContentEncoding             ,
       0x00005031 => ContentEncodingOrder        ,
       0x00005032 => ContentEncodingScope        ,
       0x00005033 => ContentEncodingType         ,
       0x00005034 => ContentCompression          ,
       0x00004254 => ContentCompAlgo             ,
       0x00004255 => ContentCompSettings         ,
       0x00005035 => ContentEncryption           ,
       0x000047E1 => ContentEncAlgo              ,
       0x000047E2 => ContentEncKeyID             ,
       0x000047E3 => ContentSignature            ,
       0x000047E4 => ContentSigKeyID             ,
       0x000047E5 => ContentSigAlgo              ,
       0x000047E6 => ContentSigHashAlgo          ,
       0x1C53BB6B => Cues                        ,
       0x000000BB => CuePoint                    ,
       0x000000B3 => CueTime                     ,
       0x000000B7 => CueTrackPositions           ,
       0x000000F7 => CueTrack                    ,
       0x000000F1 => CueClusterPosition          ,
       0x00005378 => CueBlockNumber              ,
       0x000000EA => CueCodecState               ,
       0x000000DB => CueReference                ,
       0x00000096 => CueRefTime                  ,
       0x00000097 => CueRefCluster               ,
       0x0000535F => CueRefNumber                ,
       0x000000EB => CueRefCodecState            ,
       0x1941A469 => Attachments                 ,
       0x000061A7 => AttachedFile                ,
       0x0000467E => FileDescription             ,
       0x0000466E => FileName                    ,
       0x00004660 => FileMimeType                ,
       0x0000465C => FileData                    ,
       0x000046AE => FileUID                     ,
       0x00004675 => FileReferral                ,
       0x00004661 => FileUsedStartTime           ,
       0x00004662 => FileUsedEndTime             ,
       0x1043A770 => Chapters                    ,
       0x000045B9 => EditionEntry                ,
       0x000045BC => EditionUID                  ,
       0x000045BD => EditionFlagHidden           ,
       0x000045DB => EditionFlagDefault          ,
       0x000045DD => EditionFlagOrdered          ,
       0x000000B6 => ChapterAtom                 ,
       0x000073C4 => ChapterUID                  ,
       0x00000091 => ChapterTimeStart            ,
       0x00000092 => ChapterTimeEnd              ,
       0x00000098 => ChapterFlagHidden           ,
       0x00004598 => ChapterFlagEnabled          ,
       0x00006E67 => ChapterSegmentUID           ,
       0x00006EBC => ChapterSegmentEditionUID    ,
       0x000063C3 => ChapterPhysicalEquiv        ,
       0x0000008F => ChapterTrack                ,
       0x00000089 => ChapterTrackNumber          ,
       0x00000080 => ChapterDisplay              ,
       0x00000085 => ChapString                  ,
       0x0000437C => ChapLanguage                ,
       0x0000437E => ChapCountry                 ,
       0x00006944 => ChapProcess                 ,
       0x00006955 => ChapProcessCodecID          ,
       0x0000450D => ChapProcessPrivate          ,
       0x00006911 => ChapProcessCommand          ,
       0x00006922 => ChapProcessTime             ,
       0x00006933 => ChapProcessData             ,
       0x1254C367 => Tags                        ,
       0x00007373 => Tag                         ,
       0x000063C0 => Targets                     ,
       0x000068CA => TargetTypeValue             ,
       0x000063CA => TargetType                  ,
       0x000063C5 => TagTrackUID                 ,
       0x000063C9 => TagEditionUID               ,
       0x000063C4 => TagChapterUID               ,
       0x000063C6 => TagAttachmentUID            ,
       0x000067C8 => SimpleTag                   ,
       0x000045A3 => TagName                     ,
       0x0000447A => TagLanguage                 ,
       0x00004484 => TagDefault                  ,
       0x00004487 => TagString                   ,
       0x00004485 => TagBinary                   ,
       _ => Unknown,
    }
}

pub fn class_to_id(c:Class) -> u64 {
    use self::Class::*;
    
    match c {
        EBML                        => 0x1A45DFA3,
        EBMLVersion                 => 0x00004286,
        EBMLReadVersion             => 0x000042F7,
        EBMLMaxIDLength             => 0x000042F2,
        EBMLMaxSizeLength           => 0x000042F3,
        DocType                     => 0x00004282,
        DocTypeVersion              => 0x00004287,
        DocTypeReadVersion          => 0x00004285,
        Void                        => 0x000000EC,
        CRC32                       => 0x000000BF,
        SignatureSlot               => 0x1B538667,
        SignatureAlgo               => 0x00007E8A,
        SignatureHash               => 0x00007E9A,
        SignaturePublicKey          => 0x00007EA5,
        Signature                   => 0x00007EB5,
        SignatureElements           => 0x00007E5B,
        SignatureElementList        => 0x00007E7B,
        SignedElement               => 0x00006532,
        Segment                     => 0x18538067,
        SeekHead                    => 0x114D9B74,
        Seek                        => 0x00004DBB,
        SeekID                      => 0x000053AB,
        SeekPosition                => 0x000053AC,
        Info                        => 0x1549A966,
        SegmentUID                  => 0x000073A4,
        SegmentFilename             => 0x00007384,
        PrevUID                     => 0x003CB923,
        PrevFilename                => 0x003C83AB,
        NextUID                     => 0x003EB923,
        NextFilename                => 0x003E83BB,
        SegmentFamily               => 0x00004444,
        ChapterTranslate            => 0x00006924,
        ChapterTranslateEditionUID  => 0x000069FC,
        ChapterTranslateCodec       => 0x000069BF,
        ChapterTranslateID          => 0x000069A5,
        TimecodeScale               => 0x002AD7B1,
        Duration                    => 0x00004489,
        DateUTC                     => 0x00004461,
        Title                       => 0x00007BA9,
        MuxingApp                   => 0x00004D80,
        WritingApp                  => 0x00005741,
        Cluster                     => 0x1F43B675,
        Timecode                    => 0x000000E7,
        SilentTracks                => 0x00005854,
        SilentTrackNumber           => 0x000058D7,
        Position                    => 0x000000A7,
        PrevSize                    => 0x000000AB,
        SimpleBlock                 => 0x000000A3,
        BlockGroup                  => 0x000000A0,
        Block                       => 0x000000A1,
        BlockVirtual                => 0x000000A2,
        BlockAdditions              => 0x000075A1,
        BlockMore                   => 0x000000A6,
        BlockAddID                  => 0x000000EE,
        BlockAdditional             => 0x000000A5,
        BlockDuration               => 0x0000009B,
        ReferencePriority           => 0x000000FA,
        ReferenceBlock              => 0x000000FB,
        ReferenceVirtual            => 0x000000FD,
        CodecState                  => 0x000000A4,
        Slices                      => 0x0000008E,
        TimeSlice                   => 0x000000E8,
        LaceNumber                  => 0x000000CC,
        FrameNumber                 => 0x000000CD,
        BlockAdditionID             => 0x000000CB,
        Delay                       => 0x000000CE,
        SliceDuration               => 0x000000CF,
        ReferenceFrame              => 0x000000C8,
        ReferenceOffset             => 0x000000C9,
        ReferenceTimeCode           => 0x000000CA,
        EncryptedBlock              => 0x000000AF,
        Tracks                      => 0x1654AE6B,
        TrackEntry                  => 0x000000AE,
        TrackNumber                 => 0x000000D7,
        TrackUID                    => 0x000073C5,
        TrackType                   => 0x00000083,
        FlagEnabled                 => 0x000000B9,
        FlagDefault                 => 0x00000088,
        FlagForced                  => 0x000055AA,
        FlagLacing                  => 0x0000009C,
        MinCache                    => 0x00006DE7,
        MaxCache                    => 0x00006DF8,
        DefaultDuration             => 0x0023E383,
        TrackTimecodeScale          => 0x0023314F,
        TrackOffset                 => 0x0000537F,
        MaxBlockAdditionID          => 0x000055EE,
        Name                        => 0x0000536E,
        Language                    => 0x0022B59C,
        CodecID                     => 0x00000086,
        CodecPrivate                => 0x000063A2,
        CodecName                   => 0x00258688,
        AttachmentLink              => 0x00007446,
        CodecSettings               => 0x003A9697,
        CodecInfoURL                => 0x003B4040,
        CodecDownloadURL            => 0x0026B240,
        CodecDecodeAll              => 0x000000AA,
        TrackOverlay                => 0x00006FAB,
        TrackTranslate              => 0x00006624,
        TrackTranslateEditionUID    => 0x000066FC,
        TrackTranslateCodec         => 0x000066BF,
        TrackTranslateTrackID       => 0x000066A5,
        Video                       => 0x000000E0,
        FlagInterlaced              => 0x0000009A,
        StereoMode                  => 0x000053B8,
        OldStereoMode               => 0x000053B9,
        PixelWidth                  => 0x000000B0,
        PixelHeight                 => 0x000000BA,
        PixelCropBottom             => 0x000054AA,
        PixelCropTop                => 0x000054BB,
        PixelCropLeft               => 0x000054CC,
        PixelCropRight              => 0x000054DD,
        DisplayWidth                => 0x000054B0,
        DisplayHeight               => 0x000054BA,
        DisplayUnit                 => 0x000054B2,
        AspectRatioType             => 0x000054B3,
        ColourSpace                 => 0x002EB524,
        GammaValue                  => 0x002FB523,
        FrameRate                   => 0x002383E3,
        Audio                       => 0x000000E1,
        SamplingFrequency           => 0x000000B5,
        OutputSamplingFrequency     => 0x000078B5,
        Channels                    => 0x0000009F,
        ChannelPositions            => 0x00007D7B,
        BitDepth                    => 0x00006264,
        TrackOperation              => 0x000000E2,
        TrackCombinePlanes          => 0x000000E3,
        TrackPlane                  => 0x000000E4,
        TrackPlaneUID               => 0x000000E5,
        TrackPlaneType              => 0x000000E6,
        TrackJoinBlocks             => 0x000000E9,
        TrackJoinUID                => 0x000000ED,
        TrickTrackUID               => 0x000000C0,
        TrickTrackSegmentUID        => 0x000000C1,
        TrickTrackFlag              => 0x000000C6,
        TrickMasterTrackUID         => 0x000000C7,
        TrickMasterTrackSegmentUID  => 0x000000C4,
        ContentEncodings            => 0x00006D80,
        ContentEncoding             => 0x00006240,
        ContentEncodingOrder        => 0x00005031,
        ContentEncodingScope        => 0x00005032,
        ContentEncodingType         => 0x00005033,
        ContentCompression          => 0x00005034,
        ContentCompAlgo             => 0x00004254,
        ContentCompSettings         => 0x00004255,
        ContentEncryption           => 0x00005035,
        ContentEncAlgo              => 0x000047E1,
        ContentEncKeyID             => 0x000047E2,
        ContentSignature            => 0x000047E3,
        ContentSigKeyID             => 0x000047E4,
        ContentSigAlgo              => 0x000047E5,
        ContentSigHashAlgo          => 0x000047E6,
        Cues                        => 0x1C53BB6B,
        CuePoint                    => 0x000000BB,
        CueTime                     => 0x000000B3,
        CueTrackPositions           => 0x000000B7,
        CueTrack                    => 0x000000F7,
        CueClusterPosition          => 0x000000F1,
        CueBlockNumber              => 0x00005378,
        CueCodecState               => 0x000000EA,
        CueReference                => 0x000000DB,
        CueRefTime                  => 0x00000096,
        CueRefCluster               => 0x00000097,
        CueRefNumber                => 0x0000535F,
        CueRefCodecState            => 0x000000EB,
        Attachments                 => 0x1941A469,
        AttachedFile                => 0x000061A7,
        FileDescription             => 0x0000467E,
        FileName                    => 0x0000466E,
        FileMimeType                => 0x00004660,
        FileData                    => 0x0000465C,
        FileUID                     => 0x000046AE,
        FileReferral                => 0x00004675,
        FileUsedStartTime           => 0x00004661,
        FileUsedEndTime             => 0x00004662,
        Chapters                    => 0x1043A770,
        EditionEntry                => 0x000045B9,
        EditionUID                  => 0x000045BC,
        EditionFlagHidden           => 0x000045BD,
        EditionFlagDefault          => 0x000045DB,
        EditionFlagOrdered          => 0x000045DD,
        ChapterAtom                 => 0x000000B6,
        ChapterUID                  => 0x000073C4,
        ChapterTimeStart            => 0x00000091,
        ChapterTimeEnd              => 0x00000092,
        ChapterFlagHidden           => 0x00000098,
        ChapterFlagEnabled          => 0x00004598,
        ChapterSegmentUID           => 0x00006E67,
        ChapterSegmentEditionUID    => 0x00006EBC,
        ChapterPhysicalEquiv        => 0x000063C3,
        ChapterTrack                => 0x0000008F,
        ChapterTrackNumber          => 0x00000089,
        ChapterDisplay              => 0x00000080,
        ChapString                  => 0x00000085,
        ChapLanguage                => 0x0000437C,
        ChapCountry                 => 0x0000437E,
        ChapProcess                 => 0x00006944,
        ChapProcessCodecID          => 0x00006955,
        ChapProcessPrivate          => 0x0000450D,
        ChapProcessCommand          => 0x00006911,
        ChapProcessTime             => 0x00006922,
        ChapProcessData             => 0x00006933,
        Tags                        => 0x1254C367,
        Tag                         => 0x00007373,
        Targets                     => 0x000063C0,
        TargetTypeValue             => 0x000068CA,
        TargetType                  => 0x000063CA,
        TagTrackUID                 => 0x000063C5,
        TagEditionUID               => 0x000063C9,
        TagChapterUID               => 0x000063C4,
        TagAttachmentUID            => 0x000063C6,
        SimpleTag                   => 0x000067C8,
        TagName                     => 0x000045A3,
        TagLanguage                 => 0x0000447A,
        TagDefault                  => 0x00004484,
        TagString                   => 0x00004487,
        TagBinary                   => 0x00004485,
        Unknown => panic!("Trying to get ID of Unknown Matroska class"),
    }
}

pub fn class_to_type(c:Class) -> ::mkv::ElementType {
    use self::Class::*;
    
    match c {
        EBML                       => Master       ,
        EBMLVersion                => Unsigned     ,
        EBMLReadVersion            => Unsigned     ,
        EBMLMaxIDLength            => Unsigned     ,
        EBMLMaxSizeLength          => Unsigned     ,
        DocType                    => TextAscii    ,
        DocTypeVersion             => Unsigned     ,
        DocTypeReadVersion         => Unsigned     ,
        Void                       => Binary       ,
        CRC32                      => Binary       ,
        SignatureSlot              => Master       ,
        SignatureAlgo              => Unsigned     ,
        SignatureHash              => Unsigned     ,
        SignaturePublicKey         => Binary       ,
        Signature                  => Binary       ,
        SignatureElements          => Master       ,
        SignatureElementList       => Master       ,
        SignedElement              => Binary       ,
        Segment                    => Master      ,
        SeekHead                   => Master       ,
        Seek                       => Master       ,
        SeekID                     => Binary       ,
        SeekPosition               => Unsigned     ,
        Info                       => Master       ,
        SegmentUID                 => Binary       ,
        SegmentFilename            => TextUtf8     ,
        PrevUID                    => Binary       ,
        PrevFilename               => TextUtf8     ,
        NextUID                    => Binary       ,
        NextFilename               => TextUtf8     ,
        SegmentFamily              => Binary       ,
        ChapterTranslate           => Master       ,
        ChapterTranslateEditionUID => Unsigned     ,
        ChapterTranslateCodec      => Unsigned     ,
        ChapterTranslateID         => Binary       ,
        TimecodeScale              => Unsigned     ,
        Duration                   => Float        ,
        DateUTC                    => Date         ,
        Title                      => TextUtf8     ,
        MuxingApp                  => TextUtf8     ,
        WritingApp                 => TextUtf8     ,
        Cluster                    => Master       ,
        Timecode                   => Unsigned     ,
        SilentTracks               => Master       ,
        SilentTrackNumber          => Unsigned     ,
        Position                   => Unsigned     ,
        PrevSize                   => Unsigned     ,
        SimpleBlock                => Binary       ,
        BlockGroup                 => Master       ,
        Block                      => Binary       ,
        BlockVirtual               => Binary       ,
        BlockAdditions             => Master       ,
        BlockMore                  => Master       ,
        BlockAddID                 => Unsigned     ,
        BlockAdditional            => Binary       ,
        BlockDuration              => Unsigned     ,
        ReferencePriority          => Unsigned     ,
        ReferenceBlock             => Signed       ,
        ReferenceVirtual           => Signed       ,
        CodecState                 => Binary       ,
        Slices                     => Master       ,
        TimeSlice                  => Master       ,
        LaceNumber                 => Unsigned     ,
        FrameNumber                => Unsigned     ,
        BlockAdditionID            => Unsigned     ,
        Delay                      => Unsigned     ,
        SliceDuration              => Unsigned     ,
        ReferenceFrame             => Master       ,
        ReferenceOffset            => Unsigned     ,
        ReferenceTimeCode          => Unsigned     ,
        EncryptedBlock             => Binary       ,
        Tracks                     => Master       ,
        TrackEntry                 => Master       ,
        TrackNumber                => Unsigned     ,
        TrackUID                   => Unsigned     ,
        TrackType                  => Unsigned     ,
        FlagEnabled                => Unsigned     ,
        FlagDefault                => Unsigned     ,
        FlagForced                 => Unsigned     ,
        FlagLacing                 => Unsigned     ,
        MinCache                   => Unsigned     ,
        MaxCache                   => Unsigned     ,
        DefaultDuration            => Unsigned     ,
        TrackTimecodeScale         => Float        ,
        TrackOffset                => Signed       ,
        MaxBlockAdditionID         => Unsigned     ,
        Name                       => TextUtf8     ,
        Language                   => TextAscii    ,
        CodecID                    => TextAscii    ,
        CodecPrivate               => Binary       ,
        CodecName                  => TextUtf8     ,
        AttachmentLink             => Unsigned     ,
        CodecSettings              => TextUtf8     ,
        CodecInfoURL               => TextAscii    ,
        CodecDownloadURL           => TextAscii    ,
        CodecDecodeAll             => Unsigned     ,
        TrackOverlay               => Unsigned     ,
        TrackTranslate             => Master       ,
        TrackTranslateEditionUID   => Unsigned     ,
        TrackTranslateCodec        => Unsigned     ,
        TrackTranslateTrackID      => Binary       ,
        Video                      => Master       ,
        FlagInterlaced             => Unsigned     ,
        StereoMode                 => Unsigned     ,
        OldStereoMode              => Unsigned     ,
        PixelWidth                 => Unsigned     ,
        PixelHeight                => Unsigned     ,
        PixelCropBottom            => Unsigned     ,
        PixelCropTop               => Unsigned     ,
        PixelCropLeft              => Unsigned     ,
        PixelCropRight             => Unsigned     ,
        DisplayWidth               => Unsigned     ,
        DisplayHeight              => Unsigned     ,
        DisplayUnit                => Unsigned     ,
        AspectRatioType            => Unsigned     ,
        ColourSpace                => Binary       ,
        GammaValue                 => Float        ,
        FrameRate                  => Float        ,
        Audio                      => Master       ,
        SamplingFrequency          => Float        ,
        OutputSamplingFrequency    => Float        ,
        Channels                   => Unsigned     ,
        ChannelPositions           => Binary       ,
        BitDepth                   => Unsigned     ,
        TrackOperation             => Master       ,
        TrackCombinePlanes         => Master       ,
        TrackPlane                 => Master       ,
        TrackPlaneUID              => Unsigned     ,
        TrackPlaneType             => Unsigned     ,
        TrackJoinBlocks            => Master       ,
        TrackJoinUID               => Unsigned     ,
        TrickTrackUID              => Unsigned     ,
        TrickTrackSegmentUID       => Binary       ,
        TrickTrackFlag             => Unsigned     ,
        TrickMasterTrackUID        => Unsigned     ,
        TrickMasterTrackSegmentUID => Binary       ,
        ContentEncodings           => Master       ,
        ContentEncoding            => Master       ,
        ContentEncodingOrder       => Unsigned     ,
        ContentEncodingScope       => Unsigned     ,
        ContentEncodingType        => Unsigned     ,
        ContentCompression         => Master       ,
        ContentCompAlgo            => Unsigned     ,
        ContentCompSettings        => Binary       ,
        ContentEncryption          => Master       ,
        ContentEncAlgo             => Unsigned     ,
        ContentEncKeyID            => Binary       ,
        ContentSignature           => Binary       ,
        ContentSigKeyID            => Binary       ,
        ContentSigAlgo             => Unsigned     ,
        ContentSigHashAlgo         => Unsigned     ,
        Cues                       => Master       ,
        CuePoint                   => Master       ,
        CueTime                    => Unsigned     ,
        CueTrackPositions          => Master       ,
        CueTrack                   => Unsigned     ,
        CueClusterPosition         => Unsigned     ,
        CueBlockNumber             => Unsigned     ,
        CueCodecState              => Unsigned     ,
        CueReference               => Master       ,
        CueRefTime                 => Unsigned     ,
        CueRefCluster              => Unsigned     ,
        CueRefNumber               => Unsigned     ,
        CueRefCodecState           => Unsigned     ,
        Attachments                => Master       ,
        AttachedFile               => Master       ,
        FileDescription            => TextUtf8     ,
        FileName                   => TextUtf8     ,
        FileMimeType               => TextAscii    ,
        FileData                   => Binary       ,
        FileUID                    => Unsigned     ,
        FileReferral               => Binary       ,
        FileUsedStartTime          => Unsigned     ,
        FileUsedEndTime            => Unsigned     ,
        Chapters                   => Master       ,
        EditionEntry               => Master       ,
        EditionUID                 => Unsigned     ,
        EditionFlagHidden          => Unsigned     ,
        EditionFlagDefault         => Unsigned     ,
        EditionFlagOrdered         => Unsigned     ,
        ChapterAtom                => Master       ,
        ChapterUID                 => Unsigned     ,
        ChapterTimeStart           => Unsigned     ,
        ChapterTimeEnd             => Unsigned     ,
        ChapterFlagHidden          => Unsigned     ,
        ChapterFlagEnabled         => Unsigned     ,
        ChapterSegmentUID          => Binary       ,
        ChapterSegmentEditionUID   => Unsigned     ,
        ChapterPhysicalEquiv       => Unsigned     ,
        ChapterTrack               => Master       ,
        ChapterTrackNumber         => Unsigned     ,
        ChapterDisplay             => Master       ,
        ChapString                 => TextUtf8     ,
        ChapLanguage               => TextAscii    ,
        ChapCountry                => TextAscii    ,
        ChapProcess                => Master       ,
        ChapProcessCodecID         => Unsigned     ,
        ChapProcessPrivate         => Binary       ,
        ChapProcessCommand         => Master       ,
        ChapProcessTime            => Unsigned     ,
        ChapProcessData            => Binary       ,
        Tags                       => Master       ,
        Tag                        => Master       ,
        Targets                    => Master       ,
        TargetTypeValue            => Unsigned     ,
        TargetType                 => TextAscii    ,
        TagTrackUID                => Unsigned     ,
        TagEditionUID              => Unsigned     ,
        TagChapterUID              => Unsigned     ,
        TagAttachmentUID           => Unsigned     ,
        SimpleTag                  => Master       ,
        TagName                    => TextUtf8     ,
        TagLanguage                => TextAscii    ,
        TagDefault                 => Unsigned     ,
        TagString                  => TextUtf8     ,
        TagBinary                  => Binary       ,
        Unknown => Binary
    }
}


#[test]
fn eldb_test__id_to_class() {
    assert_eq!(id_to_class(0x1A45DFA3), Class::EBML);
    assert_eq!(id_to_class(0x002EB524), Class::ColourSpace);
    assert_eq!(id_to_class(0x000000EC), Class::Void);
    assert_eq!(id_to_class(0x00004285), Class::DocTypeReadVersion);
    assert_eq!(id_to_class(0x1A45DBBBB), Class::Unknown);
}

#[test]
fn eldb_test__class_to_id() {
    assert_eq!(class_to_id(Class::EBML              ), 0x1A45DFA3);
    assert_eq!(class_to_id(Class::ColourSpace       ), 0x002EB524);
    assert_eq!(class_to_id(Class::Void              ), 0x000000EC);
    assert_eq!(class_to_id(Class::DocTypeReadVersion), 0x00004285);
}

#[test]
fn eldb_test__class_to_type() {
    use ::mkv::ElementType::*;
    assert_eq!(class_to_type(Class::EBML              ), Master);
    assert_eq!(class_to_type(Class::ColourSpace       ), Binary);
    assert_eq!(class_to_type(Class::Void              ), Binary);
    assert_eq!(class_to_type(Class::DocTypeReadVersion), Unsigned);
}
